name: practica_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - media/images/background.jpg
    - media/images/noteicon.png
  fonts:
    - family: Monserga
      fonts:
        - asset: media/fonts/Monserga-regular.ttf
    - family: Typoround
      fonts:
        - asset: media/fonts/Typo_Round_Bold.otf
        - asset: media/fonts/Typo_Round_regular.otf
